server:
  port: ${MSVC_COSTOS_PORT:8020}

spring:
  application:
    name: msvc-puntos-costos

  cache:
    type: redis
  data:
    redis:
      host: redis
      port: ${REDIS_PORT}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka

  instance:
    prefer-ip-address: true
    hostname: msvc-puntos-ventas
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${MSVC_COSTOS_PORT}

services:
  msvc-puntos-ventas:
    url: http://msvc-puntos-ventas

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        failure-rate-threshold: 50