server:
  port: 8010

spring:
  application:
    name: msvc-puntos-ventas

  cache:
    type: redis
  data:
    redis:
      host: localhost 
      port: 6379

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true
    hostname: msvc-puntos-ventas
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${server.port}
    
    

# springdoc:
#   swagger-ui:
#     path: ${spring.application.name}/swagger-ui.html
