server:
  port: 8030

spring:
  application:
    name: msvc-acreditaciones

  datasource:
    url: jdbc:mysql://localhost:3306/DBAcreditaciones?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true
    hostname: msvc-acreditaciones
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.uuid}

services:
  msvc-puntos-ventas:
    url: http://msvc-puntos-ventas

# springdoc:
#   swagger-ui:
#     path: ${spring.application.name}/swagger-ui.html